#!/usr/bin/env node

var mblib = require('./');
var program = require('commander');
var package = require('./package.json');

program.version(package.version)
  .usage('[options] mbtiles outpath')
  .option('-p, --parallel [n]', 'max number of parallel writes', 50)
  .parse(process.argv);
if (program.args.length < 2) {
  program.help();
}
mblib(program.args[0], program.args[1], program.connections, function (err, resp) {
  if (err) {
    console.error(err);
    process.exit(1);
  } else {
    console.log('done');
    console.log(resp);
    process.exit(0)
  }
});